"""
Secret storage for Ixel MAT.

Stores API keys in ~/.config/ixel-mat/.env (chmod 600).
Loads automatically on startup — no manual export needed.

Flow:
  1. `ixel-mat setup` → interactive wizard, saves to .env
  2. On startup, loader reads .env and injects into os.environ
  3. Config TOML references keys by env var name (token_env)
  4. User never types `export` again
"""
from __future__ import annotations

import os
import stat
from pathlib import Path

_ENV_DIR  = Path.home() / ".config" / "ixel-mat"
_ENV_FILE = _ENV_DIR / ".env"


def load_env() -> dict[str, str]:
    """
    Load secrets from .env file into os.environ.
    Returns dict of loaded key names → values.
    Does NOT override already-set env vars (explicit export wins).
    """
    loaded: dict[str, str] = {}

    if not _ENV_FILE.exists():
        return loaded

    try:
        for line in _ENV_FILE.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                continue
            key, _, value = line.partition("=")
            key = key.strip()
            value = value.strip().strip('"').strip("'")
            if key and value:
                # Don't override already-set vars
                if key not in os.environ:
                    os.environ[key] = value
                loaded[key] = value
    except Exception:
        pass

    return loaded


def save_secret(key: str, value: str) -> None:
    """Save or update a single secret in the .env file."""
    _ENV_DIR.mkdir(parents=True, exist_ok=True)

    # Read existing
    existing: dict[str, str] = {}
    comments: list[str] = []
    if _ENV_FILE.exists():
        for line in _ENV_FILE.read_text().splitlines():
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                comments.append(line)
                continue
            if "=" in stripped:
                k, _, v = stripped.partition("=")
                existing[k.strip()] = v.strip().strip('"').strip("'")

    existing[key] = value

    # Write back
    lines = [
        "# Ixel MAT — Secrets",
        "# This file is auto-generated by `ixel-mat setup`",
        "# Permissions: 600 (owner read/write only)",
        "",
    ]
    for k, v in sorted(existing.items()):
        lines.append(f'{k}="{v}"')

    _ENV_FILE.write_text("\n".join(lines) + "\n")
    _ENV_FILE.chmod(stat.S_IRUSR | stat.S_IWUSR)  # 600


def get_env_file_path() -> Path:
    return _ENV_FILE


def secrets_exist() -> bool:
    return _ENV_FILE.exists() and _ENV_FILE.stat().st_size > 50
