"""
Interactive setup wizard for Ixel MAT.
Run with: python3 mat.py setup  (or ixel-mat setup)

Sets up:
  1. Gateway token (for OpenClaw WebSocket agents)
  2. API keys (for direct HTTP agents)
  3. Agent configuration
  4. Writes ~/.config/ixel-mat/.env + config.toml
"""
from __future__ import annotations

import os
import shutil
from pathlib import Path

from rich.console import Console
from rich.prompt import Prompt, Confirm

from config.secrets import save_secret, get_env_file_path, _ENV_DIR

console = Console()

_CONFIG_DIR = Path.home() / ".config" / "ixel-mat"
_CONFIG_FILE = _CONFIG_DIR / "config.toml"

# IxelOS palette
C = {
    "moon":   "#c8d8e8",
    "blue":   "#7eb8d4",
    "violet": "#9b7fc7",
    "gold":   "#d4af37",
    "dim":    "#6b7d94",
    "green":  "#4ade80",
    "red":    "#e05252",
}


def run_setup():
    """Interactive setup wizard."""
    console.print(f"\n  [{C['gold']}]Ixel MAT[/] [{C['dim']}]— Setup Wizard[/]\n")
    console.print(f"  [{C['dim']}]This will configure your agents and API keys.[/]")
    console.print(f"  [{C['dim']}]Secrets are stored in {get_env_file_path()} (permissions: 600)[/]\n")

    _CONFIG_DIR.mkdir(parents=True, exist_ok=True)

    agents_toml: list[str] = []

    # ── Step 1: OpenClaw Gateway ──────────────────────────────────────────
    console.print(f"  [{C['blue']}]Step 1: OpenClaw Gateway[/]")
    console.print(f"  [{C['dim']}]If you have OpenClaw running locally, enter your gateway token.[/]")
    console.print(f"  [{C['dim']}]Find it at: http://127.0.0.1:18789 → Settings → Auth Token[/]\n")

    has_openclaw = Confirm.ask(f"  [{C['moon']}]Do you have OpenClaw running?[/]", default=True)

    if has_openclaw:
        token = Prompt.ask(f"  [{C['moon']}]Gateway token[/]")
        if token.strip():
            save_secret("IXELMAT_GATEWAY_TOKEN", token.strip())
            os.environ["IXELMAT_GATEWAY_TOKEN"] = token.strip()
            console.print(f"  [{C['green']}]✓[/] [{C['dim']}]Token saved[/]\n")

            # Add default OpenClaw agents
            agents_toml.append("""
[agents.jose]
type = "websocket"
url = "ws://127.0.0.1:18789"
token_env = "IXELMAT_GATEWAY_TOKEN"
session_key = "agent:main:main"
label = "Main Agent (OpenClaw)"
color = "cyan"

[agents.hermes]
type = "websocket"
url = "ws://127.0.0.1:18789"
token_env = "IXELMAT_GATEWAY_TOKEN"
session_key = "agent:hermes:main"
label = "Hermes (OpenClaw)"
color = "yellow"
""")
        else:
            console.print(f"  [{C['dim']}]Skipped[/]\n")

    # ── Step 2: Direct API Keys ───────────────────────────────────────────
    console.print(f"  [{C['blue']}]Step 2: Direct API Agents (optional)[/]")
    console.print(f"  [{C['dim']}]Add API keys for direct access — no gateway needed.[/]\n")

    api_providers = [
        ("OpenAI (GPT)", "OPENAI_API_KEY", "https://api.openai.com/v1/chat/completions", "gpt-4o", "green", "gpt"),
        ("xAI (Grok)", "XAI_API_KEY", "https://api.x.ai/v1/chat/completions", "grok-4", "magenta", "grok"),
        ("Anthropic (Claude)", "ANTHROPIC_API_KEY", "https://api.anthropic.com/v1/messages", "claude-sonnet-4-5", "blue", "claude"),
        ("Google (Gemini)", "GOOGLE_API_KEY", "https://generativelanguage.googleapis.com/v1beta/openai/chat/completions", "gemini-2.5-pro", "red", "gemini"),
    ]

    for label, env_name, url, model, color, agent_id in api_providers:
        existing = os.getenv(env_name, "")
        if existing:
            console.print(f"  [{C['green']}]✓[/] [{C['moon']}]{label}[/] [{C['dim']}]already set ({env_name})[/]")
            add = Confirm.ask(f"    [{C['dim']}]Add as agent?[/]", default=True)
        else:
            add_key = Confirm.ask(f"  [{C['moon']}]Add {label}?[/]", default=False)
            if not add_key:
                continue
            key = Prompt.ask(f"    [{C['moon']}]API key[/]")
            if not key.strip():
                continue
            save_secret(env_name, key.strip())
            os.environ[env_name] = key.strip()
            console.print(f"    [{C['green']}]✓[/] [{C['dim']}]Key saved[/]")
            add = True

        if add:
            agents_toml.append(f"""
[agents.{agent_id}]
type = "http"
url = "{url}"
token_env = "{env_name}"
model = "{model}"
label = "{label}"
color = "{color}"
""")
            console.print(f"    [{C['green']}]✓[/] [{C['dim']}]{label} added as agent[/]")

    console.print()

    # ── Step 3: Write config ──────────────────────────────────────────────
    if agents_toml:
        config_content = "# Ixel MAT — Agent Configuration\n# Generated by setup wizard\n# Secrets stored in .env (not here)\n"
        config_content += "\n".join(agents_toml)

        # Backup existing config
        if _CONFIG_FILE.exists():
            backup = _CONFIG_FILE.with_suffix(".toml.bak")
            shutil.copy2(_CONFIG_FILE, backup)
            console.print(f"  [{C['dim']}]Backed up existing config to {backup}[/]")

        _CONFIG_FILE.write_text(config_content)
        console.print(f"  [{C['green']}]✓[/] [{C['dim']}]Config written to {_CONFIG_FILE}[/]")

    # ── Done ──────────────────────────────────────────────────────────────
    console.print(f"\n  [{C['gold']}]Setup complete![/]\n")
    console.print(f"  [{C['dim']}]Run Ixel MAT with:[/]")
    console.print(f"    [{C['blue']}]cd {Path(__file__).parent.parent}[/]")
    console.print(f"    [{C['blue']}]python3 mat.py[/]\n")
    console.print(f"  [{C['dim']}]No export commands needed — secrets load automatically.[/]\n")
